### ISSUE TITLE
[suggestion] Investigate altering Droid <intelligence> to "ToolUser"

### ISSUE THREAD

**Issue by darwithe** [mipen/MD2Base#27]
There are a bunch of small little things that have always bothered me about the droids. They bother you for colonist beds, they count against your population, they send alerts about being idle or damaged, and they start really cluttering up some of the interfaces.

Thus frustrated I began playing around with the files to try and fix this. So I delved the various droid defs and compared them to vanilla equivalents looking for potentially relevant tags, and doing so stumbled upon the "intelligence" tag, and in the mechanoids race file the "ToolUser" setting for it. 

As far as I can see setting this has three major effects: It removes dynamic heads(Causing a whole bunch of graphics exceptions to get thrown if you don't make some changes), it makes the droids not count as colonists when it comes to the overview interface/population count/colonist event messaging, and finally it makes you unable to equip a droid by interface (The JobGiver_OptimizeApparel in the thinktree still functions, but you can't change their settings in the outfitter, and you can't force equip a weapon/apparel) 

Other than this my testing has had the droids working splendidly.

**Comment by mipen** [comment]
Thanks very much for bringing this to my attention, I have been able to fix a lot of problems the droids had with this :D In the next release all droids will now be ToolUsers, which stops them being counted among the general population of the colony and stops all the alerts. I've made a workaround for the head graphic, and just have to work on being able to give them weapons. I never intended for droids to be able to wear apparel so it's good that you can't force them anymore. I've made a new work tab in the overview to control droids.
Anyways, thanks a lot for bringing this to my attention! :)
