### ISSUE TITLE
Droids get damaged but don't heal

### ISSUE THREAD

**Issue by schildkoei** [mipen/MD2Base#28]
I have been having trouble with some droids getting damaged but aren't able to get fully repaired back up, this in itself isn't a huge problem, the problem lies with the popup message saying my colonists need treatment on the side. Would it be possible to get some kind of a repairstation where a colonist can repair the droids, as sort of a medical bed.

**Comment by mipen** [comment]
Hi there, yah I've been meaning to do this for a long time, but it's going to be a huge and tricky job and I've been putting it off haha. In the next release the droids won't trigger alerts anymore, and I might get around to doing their repair/upgrade functionality in

**Comment by mipen** [comment]
Addressed this in the latest release :)
